addSbtPlugin("com.typesafe.play"  % "sbt-plugin"                % "2.8.8")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.5.0")
addSbtPlugin("com.vmunier"        % "sbt-web-scalajs"           % "1.1.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.0.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-gzip"                  % "1.0.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-digest"                % "1.1.4")
addSbtPlugin("com.lucidchart"     % "sbt-scalafmt"              % "1.16")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
