name: CI

on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout repo
      uses: actions/checkout@v2.3.4
    - 
      name: Set up Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - 
      name: Build and test
      run: sbt test
