name: Codacy analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codacy-analysis:
    name: Codacy analysis
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy analysis
        uses: codacy/codacy-analysis-cli-action@4.0.0
        with:
          allow-network: true
