name: Scala Steward
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD }}
          author-name: K
          author-email: 12345+octocat@users.noreply.github.com
